In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/PrismHire"

DATA_PATH = f"{PROJECT_PATH}/data"
OUTPUT_PATH = f"{PROJECT_PATH}/outputs"
MODEL_PATH = f"{PROJECT_PATH}/models"
GRAPH_PATH = f"{PROJECT_PATH}/graphs"

In [3]:
import zipfile

zip_path = f"{DATA_PATH}/challenge.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(DATA_PATH)

print("Dataset extracted!")

Dataset extracted!

In [4]:
import os

for root, dirs, files in os.walk(DATA_PATH):
    for file in files:
        print(os.path.join(root, file))

/content/drive/MyDrive/PrismHire/data/challenge.zip
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/.DS_Store
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/redrob_signals_doc.docx
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_metadata_template.yaml
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_candidates.json
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx
/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv
/content/drive/MyDrive/PrismHire/data/__MACOSX/._[PUB] India_runs_data_and_ai_challenge
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._.DS_Store
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._India_runs_data_and_ai_challenge
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._job_description.docx
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._redrob_signals_doc.docx
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._validate_submission.py
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidate_schema.json
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_metadata_template.yaml
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_spec.docx
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidates.jsonl
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_candidates.json
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._README.docx
/content/drive/MyDrive/PrismHire/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_submission.csv

candidates.jsonl ⭐⭐⭐⭐⭐

This is almost certainly the entire candidate database.

candidate_schema.json ⭐⭐⭐⭐⭐

This tells us:

what fields exist
field types
nested structures

Think of it like a database blueprint.

job_description.docx ⭐⭐⭐⭐⭐

This is the job we are matching candidates against.

We need to understand it deeply.

redrob_signals_doc.docx ⭐⭐⭐⭐⭐

This might be the most important file.

It explains behavioral signals.

Example:

profile views
response rate
offer acceptance
search appearances

sample_submission.csv ⭐⭐⭐⭐

Tells us:

output format
column names
ranking requirements

validate_submission.py ⭐⭐⭐⭐

Tells us:

exact submission format
hidden rules
constraints

Always inspect it.

In [5]:
import pandas as pd
import json
import os

In [6]:
BASE_PATH = "/content/drive/MyDrive/PrismHire/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge"

In [7]:
schema_path = f"{BASE_PATH}/candidate_schema.json"

with open(schema_path, "r") as f:
    schema = json.load(f)

print(schema)

{'$schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Redrob Candidate Profile Schema', 'description': 'Schema for a single candidate profile in the Intelligent Candidate Discovery & Ranking Challenge dataset.', 'type': 'object', 'required': ['candidate_id', 'profile', 'career_history', 'education', 'skills', 'redrob_signals'], 'properties': {'candidate_id': {'type': 'string', 'pattern': '^CAND_[0-9]{7}$', 'description': 'Unique identifier for the candidate. Format: CAND_XXXXXXX (7 digits).'}, 'profile': {'type': 'object', 'required': ['anonymized_name', 'headline', 'summary', 'location', 'country', 'years_of_experience', 'current_title', 'current_company', 'current_company_size', 'current_industry'], 'properties': {'anonymized_name': {'type': 'string', 'description': 'Anonymized full name.'}, 'headline': {'type': 'string', 'description': 'One-line professional headline.'}, 'summary': {'type': 'string', 'description': 'Multi-sentence professional summary.'}, 'location': {'type': 'string', 'description': 'City, region/state.'}, 'country': {'type': 'string'}, 'years_of_experience': {'type': 'number', 'minimum': 0, 'maximum': 50}, 'current_title': {'type': 'string'}, 'current_company': {'type': 'string'}, 'current_company_size': {'type': 'string', 'enum': ['1-10', '11-50', '51-200', '201-500', '501-1000', '1001-5000', '5001-10000', '10001+']}, 'current_industry': {'type': 'string'}}}, 'career_history': {'type': 'array', 'minItems': 1, 'maxItems': 10, 'items': {'type': 'object', 'required': ['company', 'title', 'start_date', 'end_date', 'duration_months', 'is_current', 'industry', 'company_size', 'description'], 'properties': {'company': {'type': 'string'}, 'title': {'type': 'string'}, 'start_date': {'type': 'string', 'format': 'date'}, 'end_date': {'type': ['string', 'null'], 'format': 'date'}, 'duration_months': {'type': 'integer', 'minimum': 0}, 'is_current': {'type': 'boolean'}, 'industry': {'type': 'string'}, 'company_size': {'type': 'string', 'enum': ['1-10', '11-50', '51-200', '201-500', '501-1000', '1001-5000', '5001-10000', '10001+']}, 'description': {'type': 'string', 'description': 'Role responsibilities and achievements.'}}}}, 'education': {'type': 'array', 'minItems': 0, 'maxItems': 5, 'items': {'type': 'object', 'required': ['institution', 'degree', 'field_of_study', 'start_year', 'end_year'], 'properties': {'institution': {'type': 'string'}, 'degree': {'type': 'string'}, 'field_of_study': {'type': 'string'}, 'start_year': {'type': 'integer', 'minimum': 1970, 'maximum': 2030}, 'end_year': {'type': 'integer', 'minimum': 1970, 'maximum': 2035}, 'grade': {'type': ['string', 'null'], 'description': 'GPA / percentage / class.'}, 'tier': {'type': 'string', 'enum': ['tier_1', 'tier_2', 'tier_3', 'tier_4', 'unknown'], 'description': 'Internal tiering for institution prestige.'}}}}, 'skills': {'type': 'array', 'minItems': 0, 'items': {'type': 'object', 'required': ['name', 'proficiency', 'endorsements'], 'properties': {'name': {'type': 'string'}, 'proficiency': {'type': 'string', 'enum': ['beginner', 'intermediate', 'advanced', 'expert']}, 'endorsements': {'type': 'integer', 'minimum': 0}, 'duration_months': {'type': 'integer', 'minimum': 0, 'description': 'Months the candidate has used this skill'}}}}, 'certifications': {'type': 'array', 'items': {'type': 'object', 'required': ['name', 'issuer', 'year'], 'properties': {'name': {'type': 'string'}, 'issuer': {'type': 'string'}, 'year': {'type': 'integer'}}}}, 'languages': {'type': 'array', 'items': {'type': 'object', 'required': ['language', 'proficiency'], 'properties': {'language': {'type': 'string'}, 'proficiency': {'type': 'string', 'enum': ['basic', 'conversational', 'professional', 'native']}}}}, 'redrob_signals': {'type': 'object', 'description': 'Simulated platform activity and engagement signals from the Redrob ecosystem.', 'required': ['profile_completeness_score', 'signup_date', 'last_active_date', 'open_to_work_flag', 'profile_views_received_30d', 'applications_submitted_30d', 'recruiter_response_rate', 'avg_response_time_hours', 'skill_assessment_scores', 'connection_count', 'endorsements_received', 'notice_period_days', 'expected_salary_range_inr_lpa', 'preferred_work_mode', 'willing_to_relocate', 'github_activity_score', 'search_appearance_30d', 'saved_by_recruiters_30d', 'interview_completion_rate', 'offer_acceptance_rate', 'verified_email', 'verified_phone', 'linkedin_connected'], 'properties': {'profile_completeness_score': {'type': 'number', 'minimum': 0, 'maximum': 100, 'description': 'Percentage of profile completeness.'}, 'signup_date': {'type': 'string', 'format': 'date'}, 'last_active_date': {'type': 'string', 'format': 'date'}, 'open_to_work_flag': {'type': 'boolean'}, 'profile_views_received_30d': {'type': 'integer', 'minimum': 0}, 'applications_submitted_30d': {'type': 'integer', 'minimum': 0}, 'recruiter_response_rate': {'type': 'number', 'minimum': 0, 'maximum': 1, 'description': 'Fraction of recruiter messages the candidate has responded to.'}, 'avg_response_time_hours': {'type': 'number', 'minimum': 0}, 'skill_assessment_scores': {'type': 'object', 'description': 'Dict of skill_name -> score 0-100. Assessments completed on Redrob platform.', 'additionalProperties': {'type': 'number', 'minimum': 0, 'maximum': 100}}, 'connection_count': {'type': 'integer', 'minimum': 0}, 'endorsements_received': {'type': 'integer', 'minimum': 0}, 'notice_period_days': {'type': 'integer', 'minimum': 0, 'maximum': 180}, 'expected_salary_range_inr_lpa': {'type': 'object', 'required': ['min', 'max'], 'properties': {'min': {'type': 'number', 'minimum': 0}, 'max': {'type': 'number', 'minimum': 0}}, 'description': 'Expected salary in INR Lakhs Per Annum.'}, 'preferred_work_mode': {'type': 'string', 'enum': ['remote', 'hybrid', 'onsite', 'flexible']}, 'willing_to_relocate': {'type': 'boolean'}, 'github_activity_score': {'type': 'number', 'minimum': -1, 'maximum': 100, 'description': '0-100 score based on commits, PRs, stars in last 12 months. -1 if no GitHub linked.'}, 'search_appearance_30d': {'type': 'integer', 'minimum': 0, 'description': 'Number of times profile appeared in recruiter searches in last 30 days.'}, 'saved_by_recruiters_30d': {'type': 'integer', 'minimum': 0, 'description': 'Number of recruiters who saved this profile in last 30 days.'}, 'interview_completion_rate': {'type': 'number', 'minimum': 0, 'maximum': 1, 'description': 'Fraction of scheduled interviews actually attended.'}, 'offer_acceptance_rate': {'type': 'number', 'minimum': -1, 'maximum': 1, 'description': 'Historical offer acceptance rate. -1 if no offer history.'}, 'verified_email': {'type': 'boolean'}, 'verified_phone': {'type': 'boolean'}, 'linkedin_connected': {'type': 'boolean'}}}}}

In [8]:
sample_path = f"{BASE_PATH}/sample_candidates.json"

with open(sample_path, "r") as f:
    sample = json.load(f)

print(sample)

[{'candidate_id': 'CAND_0000001', 'profile': {'anonymized_name': 'Ira Vora', 'headline': 'Backend Engineer | SQL, Spark, Cloud', 'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Toronto', 'country': 'Canada', 'years_of_experience': 6.9, 'current_title': 'Backend Engineer', 'current_company': 'Mindtree', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}, {'company': 'Dunder Mifflin', 'title': 'Analytics Engineer', 'start_date': '2019-07-03', 'end_date': '2024-01-08', 'duration_months': 55, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}], 'education': [{'institution': 'Lovely Professional University', 'degree': 'B.E.', 'field_of_study': 'Computer Science', 'start_year': 2017, 'end_year': 2020, 'grade': '8.24 CGPA', 'tier': 'tier_3'}], 'skills': [{'name': 'Tailwind', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 13}, {'name': 'NLP', 'proficiency': 'advanced', 'endorsements': 37, 'duration_months': 26}, {'name': 'Image Classification', 'proficiency': 'advanced', 'endorsements': 7, 'duration_months': 40}, {'name': 'Fine-tuning LLMs', 'proficiency': 'advanced', 'endorsements': 21, 'duration_months': 36}, {'name': 'Weights & Biases', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 30}, {'name': 'Speech Recognition', 'proficiency': 'advanced', 'endorsements': 52, 'duration_months': 33}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 8, 'duration_months': 24}, {'name': 'TTS', 'proficiency': 'advanced', 'endorsements': 56, 'duration_months': 60}, {'name': 'LoRA', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 28}, {'name': 'Apache Beam', 'proficiency': 'intermediate', 'endorsements': 4, 'duration_months': 9}, {'name': 'AWS', 'proficiency': 'beginner', 'endorsements': 5, 'duration_months': 8}, {'name': 'Flask', 'proficiency': 'beginner', 'endorsements': 15, 'duration_months': 15}, {'name': 'BentoML', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 36}, {'name': 'Milvus', 'proficiency': 'advanced', 'endorsements': 40, 'duration_months': 35}, {'name': 'GANs', 'proficiency': 'advanced', 'endorsements': 12, 'duration_months': 19}, {'name': 'Statistical Modeling', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 8}, {'name': 'GCP', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 2}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 86.9, 'signup_date': '2025-10-16', 'last_active_date': '2026-05-20', 'open_to_work_flag': True, 'profile_views_received_30d': 23, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.34, 'avg_response_time_hours': 177.8, 'skill_assessment_scores': {'NLP': 38.8, 'Image Classification': 64.8, 'Fine-tuning LLMs': 41.6, 'Speech Recognition': 53.7}, 'connection_count': 356, 'endorsements_received': 35, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': False, 'github_activity_score': 9.2, 'search_appearance_30d': 249, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.71, 'offer_acceptance_rate': 0.58, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': False}}, {'candidate_id': 'CAND_0000002', 'profile': {'anonymized_name': 'Saanvi Sethi', 'headline': 'Operations Manager | 12.5+ yrs experience', 'summary': "Professional with 12.5+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Chennai, Tamil Nadu', 'country': 'India', 'years_of_experience': 12.5, 'current_title': 'Operations Manager', 'current_company': 'Wipro', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2022-11-14', 'end_date': None, 'duration_months': 43, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.'}, {'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2021-09-13', 'end_date': '2022-11-07', 'duration_months': 14, 'is_current': False, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.'}, {'company': 'Acme Corp', 'title': 'Marketing Manager', 'start_date': '2017-03-08', 'end_date': '2021-08-14', 'duration_months': 54, 'is_current': False, 'industry': 'Manufacturing', 'company_size': '201-500', 'description': 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.'}, {'company': 'Dunder Mifflin', 'title': 'Marketing Manager', 'start_date': '2014-01-23', 'end_date': '2017-03-08', 'duration_months': 38, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'B.Sc', 'field_of_study': 'Mathematics', 'start_year': 2007, 'end_year': 2011, 'grade': '77%', 'tier': 'tier_4'}], 'skills': [{'name': 'Project Management', 'proficiency': 'intermediate', 'endorsements': 14, 'duration_months': 23}, {'name': 'React', 'proficiency': 'intermediate', 'endorsements': 6, 'duration_months': 35}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 35}, {'name': 'TypeScript', 'proficiency': 'beginner', 'endorsements': 2, 'duration_months': 3}, {'name': 'Marketing', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 11}, {'name': 'Kafka', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 16}, {'name': 'JavaScript', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 3}, {'name': 'Feature Engineering', 'proficiency': 'intermediate', 'endorsements': 11, 'duration_months': 27}, {'name': 'GCP', 'proficiency': 'intermediate', 'endorsements': 7, 'duration_months': 30}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 78.7, 'signup_date': '2025-07-28', 'last_active_date': '2025-11-12', 'open_to_work_flag': True, 'profile_views_received_30d': 7, 'applications_submitted_30d': 1, 'recruiter_response_rate': 0.29, 'avg_response_time_hours': 171.6, 'skill_assessment_scores': {}, 'connection_count': 179, 'endorsements_received': 3, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 8.8, 'max': 9.0}, 'preferred_work_mode': 'flexible', 'willing_to_relocate': False, 'github_activity_score': -1, 'search_appearance_30d': 107, 'saved_by_recruiters_30d': 10, 'interview_completion_rate': 0.62, 'offer_acceptance_rate': -1, 'verified_email': False, 'verified_phone': False, 'linkedin_connected': False}}, {'candidate_id': 'CAND_0000003', 'profile': {'anonymized_name': 'Yash Agarwal', 'headline': 'Customer Support | 1.1+ yrs experience', 'summary': "Professional with 1.1+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Austin', 'country': 'USA', 'years_of_experience': 1.1, 'current_title': 'Customer Support', 'current_company': 'TCS', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'TCS', 'title': 'Customer Support', 'start_date': '2025-05-02', 'end_date': None, 'duration_months': 13, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'M.E.', 'field_of_study': 'Chemical Engineering', 'start_year': 2005, 'end_year': 2010, 'grade': '6.82 CGPA', 'tier': 'tier_4'}, {'institution': 'Chandigarh University', 'degree': 'M.Sc', 'field_of_study': 'Information Technology', 'start_year': 2017, 'end_year': 2021, 'grade': '87%', 'tier': 'tier_3'}], 'skills': [{'name': 'Angular', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 10}, {'name': 'SEO', 'proficiency': 'beginner', 'endorsements': 11, 'duration_months': 11}, {'name': 'Excel', 'proficiency': 'intermediate', 'endorsements': 2, 'duration_months': 15}, {'name': 'Accounting', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 18}, {'name': 'Kubernetes', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 34}, {'name': 'Databricks', 'proficiency': 'beginner', 'endorsements': 14, 'duration_months': 18}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'professional'}], 'redrob_signals': {'profile_completeness_score': 31.9, 'signup_date': '2024-08-02', 'last_active_date': '2026-03-21', 'open_to_work_flag': False, 'profile_views_received_30d': 1, 'applications_submitted_30d': 9, 'recruiter_response_rate': 0.46, 'avg_response_time_hours': 119.4, 'skill_assessment_scores': {}, 'connection_count': 19, 'endorsements_received': 46, 'notice_period_days': 150, 'expected_salary_range_inr_lpa': {'min': 11.2, 'max': 18.1}, 'preferred_work_mode': 'hybrid', 'willing_to_relocate': False, 'github_activity_score': -1, 'search_appearance_30d': 28, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.86, 'offer_acceptance_rate': -1, 'verified_email': True, 'verified_phone': False, 'linkedin_connected': False}}, {'candidate_id': 'CAND_0000004', 'profile': {'anonymized_name': 'Anil Bose', 'headline': 'Marketing Manager | Driving business outcomes', 'summary': "Professional with 3.8+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Sydney', 'country': 'Australia', 'years_of_experience': 3.8, 'current_title': 'Marketing Manager', 'current_company': 'Dunder Mifflin', 'current_company_size': '201-500', 'current_industry': 'Paper Products'}, 'career_history': [{'company': 'Dunder Mifflin', 'title': 'Marketing Manager', 'start_date': '2025-04-02', 'end_date': None, 'duration_months': 14, 'is_current': True, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.'}, {'company': 'Infosys', 'title': 'Operations Manager', 'start_date': '2023-07-28', 'end_date': '2025-03-19', 'duration_months': 20, 'is_current': False, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.'}, {'company': 'Globex Inc', 'title': 'Business Analyst', 'start_date': '2022-08-02', 'end_date': '2023-05-29', 'duration_months': 10, 'is_current': False, 'industry': 'Manufacturing', 'company_size': '501-1000', 'description': 'Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement initiatives that drove a 22% productivity gain over 18 months.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'B.Tech', 'field_of_study': 'Machine Learning', 'start_year': 2015, 'end_year': 2019, 'grade': '7.72 CGPA', 'tier': 'tier_4'}, {'institution': 'Lovely Professional University', 'degree': 'Ph.D', 'field_of_study': 'Electronics', 'start_year': 2013, 'end_year': 2016, 'grade': '7.61 CGPA', 'tier': 'tier_3'}], 'skills': [{'name': 'Node.js', 'proficiency': 'intermediate', 'endorsements': 1, 'duration_months': 20}, {'name': 'Content Writing', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 3}, {'name': 'Redux', 'proficiency': 'beginner', 'endorsements': 14, 'duration_months': 8}, {'name': 'Airflow', 'proficiency': 'intermediate', 'endorsements': 11, 'duration_months': 27}, {'name': 'GraphQL', 'proficiency': 'beginner', 'endorsements': 13, 'duration_months': 2}, {'name': 'Object Detection', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 17}, {'name': 'Webpack', 'proficiency': 'beginner', 'endorsements': 10, 'duration_months': 7}, {'name': 'Six Sigma', 'proficiency': 'beginner', 'endorsements': 1, 'duration_months': 12}, {'name': 'SAP', 'proficiency': 'intermediate', 'endorsements': 6, 'duration_months': 9}, {'name': 'JavaScript', 'proficiency': 'intermediate', 'endorsements': 14, 'duration_months': 29}], 'certifications': [{'name': 'AWS Certified Cloud Practitioner', 'issuer': 'AWS', 'year': 2025}, {'name': 'Scrum Master Certified', 'issuer': 'Scrum Alliance', 'year': 2025}], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'professional'}], 'redrob_signals': {'profile_completeness_score': 28.5, 'signup_date': '2025-07-21', 'last_active_date': '2026-03-25', 'open_to_work_flag': False, 'profile_views_received_30d': 3, 'applications_submitted_30d': 9, 'recruiter_response_rate': 0.26, 'avg_response_time_hours': 104.1, 'skill_assessment_scores': {}, 'connection_count': 485, 'endorsements_received': 22, 'notice_period_days': 120, 'expected_salary_range_inr_lpa': {'min': 4.6, 'max': 6.7}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': True, 'github_activity_score': -1, 'search_appearance_30d': 5, 'saved_by_recruiters_30d': 8, 'interview_completion_rate': 0.35, 'offer_acceptance_rate': -1, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': True}}, {'candidate_id': 'CAND_0000005', 'profile': {'anonymized_name': 'Aisha Sethi', 'headline': 'Accountant | Helping teams scale', 'summary': "Professional with 11.0+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Gurgaon, Haryana', 'country': 'India', 'years_of_experience': 11.0, 'current_title': 'Accountant', 'current_company': 'Stark Industries', 'current_company_size': '1001-5000', 'current_industry': 'Manufacturing'}, 'career_history': [{'company': 'Stark Industries', 'title': 'Accountant', 'start_date': '2022-02-17', 'end_date': None, 'duration_months': 52, 'is_current': True, 'industry': 'Manufacturing', 'company_size': '1001-5000', 'description': 'Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-

In [9]:
jsonl_path = f"{BASE_PATH}/candidates.jsonl"

with open(jsonl_path, "r") as f:
    for i in range(5):
        line = f.readline()
        candidate = json.loads(line)

        print("="*80)
        print(candidate)

================================================================================
{'candidate_id': 'CAND_0000001', 'profile': {'anonymized_name': 'Ira Vora', 'headline': 'Backend Engineer | SQL, Spark, Cloud', 'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Toronto', 'country': 'Canada', 'years_of_experience': 6.9, 'current_title': 'Backend Engineer', 'current_company': 'Mindtree', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}, {'company': 'Dunder Mifflin', 'title': 'Analytics Engineer', 'start_date': '2019-07-03', 'end_date': '2024-01-08', 'duration_months': 55, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}], 'education': [{'institution': 'Lovely Professional University', 'degree': 'B.E.', 'field_of_study': 'Computer Science', 'start_year': 2017, 'end_year': 2020, 'grade': '8.24 CGPA', 'tier': 'tier_3'}], 'skills': [{'name': 'Tailwind', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 13}, {'name': 'NLP', 'proficiency': 'advanced', 'endorsements': 37, 'duration_months': 26}, {'name': 'Image Classification', 'proficiency': 'advanced', 'endorsements': 7, 'duration_months': 40}, {'name': 'Fine-tuning LLMs', 'proficiency': 'advanced', 'endorsements': 21, 'duration_months': 36}, {'name': 'Weights & Biases', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 30}, {'name': 'Speech Recognition', 'proficiency': 'advanced', 'endorsements': 52, 'duration_months': 33}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 8, 'duration_months': 24}, {'name': 'TTS', 'proficiency': 'advanced', 'endorsements': 56, 'duration_months': 60}, {'name': 'LoRA', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 28}, {'name': 'Apache Beam', 'proficiency': 'intermediate', 'endorsements': 4, 'duration_months': 9}, {'name': 'AWS', 'proficiency': 'beginner', 'endorsements': 5, 'duration_months': 8}, {'name': 'Flask', 'proficiency': 'beginner', 'endorsements': 15, 'duration_months': 15}, {'name': 'BentoML', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 36}, {'name': 'Milvus', 'proficiency': 'advanced', 'endorsements': 40, 'duration_months': 35}, {'name': 'GANs', 'proficiency': 'advanced', 'endorsements': 12, 'duration_months': 19}, {'name': 'Statistical Modeling', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 8}, {'name': 'GCP', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 2}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 86.9, 'signup_date': '2025-10-16', 'last_active_date': '2026-05-20', 'open_to_work_flag': True, 'profile_views_received_30d': 23, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.34, 'avg_response_time_hours': 177.8, 'skill_assessment_scores': {'NLP': 38.8, 'Image Classification': 64.8, 'Fine-tuning LLMs': 41.6, 'Speech Recognition': 53.7}, 'connection_count': 356, 'endorsements_received': 35, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': False, 'github_activity_score': 9.2, 'search_appearance_30d': 249, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.71, 'offer_acceptance_rate': 0.58, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': False}}
================================================================================
{'candidate_id': 'CAND_0000002', 'profile': {'anonymized_name': 'Saanvi Sethi', 'headline': 'Operations Manager | 12.5+ yrs experience', 'summary': "Professional with 12.5+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Chennai, Tamil Nadu', 'country': 'India', 'years_of_experience': 12.5, 'current_title': 'Operations Manager', 'current_company': 'Wipro', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2022-11-14', 'end_date': None, 'duration_months': 43, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.'}, {'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2021-09-13', 'end_date': '2022-11-07', 'duration_months': 14, 'is_current': False, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.'}, {'company': 'Acme Corp', 'title': 'Marketing Manager', 'start_date': '2017-03-08', 'end_date': '2021-08-14', 'duration_months': 54, 'is_current': False, 'industry': 'Manufacturing', 'company_size': '201-500', 'description': 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.'}, {'company': 'Dunder Mifflin', 'title': 'Marketing Manager', 'start_date': '2014-01-23', 'end_date': '2017-03-08', 'duration_months': 38, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'B.Sc', 'field_of_study': 'Mathematics', 'start_year': 2007, 'end_year': 2011, 'grade': '77%', 'tier': 'tier_4'}], 'skills': [{'name': 'Project Management', 'proficiency': 'intermediate', 'endorsements': 14, 'duration_months': 23}, {'name': 'React', 'proficiency': 'intermediate', 'endorsements': 6, 'duration_months': 35}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 35}, {'name': 'TypeScript', 'proficiency': 'beginner', 'endorsements': 2, 'duration_months': 3}, {'name': 'Marketing', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 11}, {'name': 'Kafka', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 16}, {'name': 'JavaScript', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 3}, {'name': 'Feature Engineering', 'proficiency': 'intermediate', 'endorsements': 11, 'duration_months': 27}, {'name': 'GCP', 'proficiency': 'intermediate', 'endorsements': 7, 'duration_months': 30}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 78.7, 'signup_date': '2025-07-28', 'last_active_date': '2025-11-12', 'open_to_work_flag': True, 'profile_views_received_30d': 7, 'applications_submitted_30d': 1, 'recruiter_response_rate': 0.29, 'avg_response_time_hours': 171.6, 'skill_assessment_scores': {}, 'connection_count': 179, 'endorsements_received': 3, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 8.8, 'max': 9.0}, 'preferred_work_mode': 'flexible', 'willing_to_relocate': False, 'github_activity_score': -1, 'search_appearance_30d': 107, 'saved_by_recruiters_30d': 10, 'interview_completion_rate': 0.62, 'offer_acceptance_rate': -1, 'verified_email': False, 'verified_phone': False, 'linkedin_connected': False}}
================================================================================
{'candidate_id': 'CAND_0000003', 'profile': {'anonymized_name': 'Yash Agarwal', 'headline': 'Customer Support | 1.1+ yrs experience', 'summary': "Professional with 1.1+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Austin', 'country': 'USA', 'years_of_experience': 1.1, 'current_title': 'Customer Support', 'current_company': 'TCS', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'TCS', 'title': 'Customer Support', 'start_date': '2025-05-02', 'end_date': None, 'duration_months': 13, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'M.E.', 'field_of_study': 'Chemical Engineering', 'start_year': 2005, 'end_year': 2010, 'grade': '6.82 CGPA', 'tier': 'tier_4'}, {'institution': 'Chandigarh University', 'degree': 'M.Sc', 'field_of_study': 'Information Technology', 'start_year': 2017, 'end_year': 2021, 'grade': '87%', 'tier': 'tier_3'}], 'skills': [{'name': 'Angular', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 10}, {'name': 'SEO', 'proficiency': 'beginner', 'endorsements': 11, 'duration_months': 11}, {'name': 'Excel', 'proficiency': 'intermediate', 'endorsements': 2, 'duration_months': 15}, {'name': 'Accounting', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 18}, {'name': 'Kubernetes', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 34}, {'name': 'Databricks', 'proficiency': 'beginner', 'endorsements': 14, 'duration_months': 18}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'professional'}], 'redrob_signals': {'profile_completeness_score': 31.9, 'signup_date': '2024-08-02', 'last_active_date': '2026-03-21', 'open_to_work_flag': False, 'profile_views_received_30d': 1, 'applications_submitted_30d': 9, 'recruiter_response_rate': 0.46, 'avg_response_time_hours': 119.4, 'skill_assessment_scores': {}, 'connection_count': 19, 'endorsements_received': 46, 'notice_period_days': 150, 'expected_salary_range_inr_lpa': {'min': 11.2, 'max': 18.1}, 'preferred_work_mode': 'hybrid', 'willing_to_relocate': False, 'github_activity_score': -1, 'search_appearance_30d': 28, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.86, 'offer_acceptance_rate': -1, 'verified_email': True, 'verified_phone': False, 'linkedin_connected': False}}
================================================================================
{'candidate_id': 'CAND_0000004', 'profile': {'anonymized_name': 'Anil Bose', 'headline': 'Marketing Manager | Driving business outcomes', 'summary': "Professional with 3.8+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Sydney', 'country': 'Australia', 'years_of_experience': 3.8, 'current_title': 'Marketing Manager', 'current_company': 'Dunder Mifflin', 'current_company_size': '201-500', 'current_industry': 'Paper Products'}, 'career_history': [{'company': 'Dunder Mifflin', 'title': 'Marketing Manager', 'start_date': '2025-04-02', 'end_date': None, 'duration_months': 14, 'is_current': True, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.'}, {'company': 'Infosys', 'title': 'Operations Manager', 'start_date': '2023-07-28', 'end_date': '2025-03-19', 'duration_months': 20, 'is_current': False, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.'}, {'company': 'Globex Inc', 'title': 'Business Analyst', 'start_date': '2022-08-02', 'end_date': '2023-05-29', 'duration_months': 10, 'is_current': False, 'industry': 'Manufacturing', 'company_size': '501-1000', 'description': 'Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement initiatives that drove a 22% productivity gain over 18 months.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'B.Tech', 'field_of_study': 'Machine Learning', 'start_year': 2015, 'end_year': 2019, 'grade': '7.72 CGPA', 'tier': 'tier_4'}, {'institution': 'Lovely Professional University', 'degree': 'Ph.D', 'field_of_study': 'Electronics', 'start_year': 2013, 'end_year': 2016, 'grade': '7.61 CGPA', 'tier': 'tier_3'}], 'skills': [{'name': 'Node.js', 'proficiency': 'intermediate', 'endorsements': 1, 'duration_months': 20}, {'name': 'Content Writing', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 3}, {'name': 'Redux', 'proficiency': 'beginner', 'endorsements': 14, 'duration_months': 8}, {'name': 'Airflow', 'proficiency': 'intermediate', 'endorsements': 11, 'duration_months': 27}, {'name': 'GraphQL', 'proficiency': 'beginner', 'endorsements': 13, 'duration_months': 2}, {'name': 'Object Detection', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 17}, {'name': 'Webpack', 'proficiency': 'beginner', 'endorsements': 10, 'duration_months': 7}, {'name': 'Six Sigma', 'proficiency': 'beginner', 'endorsements': 1, 'duration_months': 12}, {'name': 'SAP', 'proficiency': 'intermediate', 'endorsements': 6, 'duration_months': 9}, {'name': 'JavaScript', 'proficiency': 'intermediate', 'endorsements': 14, 'duration_months': 29}], 'certifications': [{'name': 'AWS Certified Cloud Practitioner', 'issuer': 'AWS', 'year': 2025}, {'name': 'Scrum Master Certified', 'issuer': 'Scrum Alliance', 'year': 2025}], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'professional'}], 'redrob_signals': {'profile_completeness_score': 28.5, 'signup_date': '2025-07-21', 'last_active_date': '2026-03-25', 'open_to_work_flag': False, 'profile_views_received_30d': 3, 'applications_submitted_30d': 9, 'recruiter_response_rate': 0.26, 'avg_response_time_hours': 104.1, 'skill_assessment_scores': {}, 'connection_count': 485, 'endorsements_received': 22, 'notice_period_days': 120, 'expected_salary_range_inr_lpa': {'min': 4.6, 'max': 6.7}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': True, 'github_activity_score': -1, 'search_appearance_30d': 5, 'saved_by_recruiters_30d': 8, 'interview_completion_rate': 0.35, 'offer_acceptance_rate': -1, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': True}}
================================================================================

In [10]:
count = 0

with open(jsonl_path, "r") as f:
    for line in f:
        count += 1

print("Total Candidates:", count)

Total Candidates: 100000

In [11]:
import pprint
pprint.pprint(candidate)

{'candidate_id': 'CAND_0000005',
 'career_history': [{'company': 'Stark Industries',
                     'company_size': '1001-5000',
                     'description': 'Business analyst at a consulting firm, '
                                    'working primarily with retail and CPG '
                                    'clients. Conducted business diagnostics, '
                                    'process re-engineering work, and digital '
                                    'transformation strategy projects. Strong '
                                    'on stakeholder management, structured '
                                    'problem-solving, and the typical '
                                    'consulting toolkit (slide-craft, Excel '
                                    'modeling, executive communication). '
                                    'Recent project work involved AI-strategy '
                                    'advisory but my own technical depth in AI '
                                    'is limited.',
                     'duration_months': 52,
                     'end_date': None,
                     'industry': 'Manufacturing',
                     'is_current': True,
                     'start_date': '2022-02-17',
                     'title': 'Accountant'},
                    {'company': 'Wipro',
                     'company_size': '10001+',
                     'description': 'Senior accounting role at a mid-sized '
                                    'company — month-end close, financial '
                                    'reporting, statutory compliance (GAAP / '
                                    'Ind-AS), and tax filings. Owned the GL, '
                                    'fixed-asset register, and the '
                                    'audit-readiness function. Managed a team '
                                    'of 3 staff accountants. Built strong '
                                    'process discipline around the close '
                                    'cycle, reducing close time from 12 days '
                                    'to 7 over the last two years.',
                     'duration_months': 45,
                     'end_date': '2022-02-03',
                     'industry': 'IT Services',
                     'is_current': False,
                     'start_date': '2018-05-25',
                     'title': 'HR Manager'},
                    {'company': 'Initech',
                     'company_size': '51-200',
                     'description': 'Business analyst at a consulting firm, '
                                    'working primarily with retail and CPG '
                                    'clients. Conducted business diagnostics, '
                                    'process re-engineering work, and digital '
                                    'transformation strategy projects. Strong '
                                    'on stakeholder management, structured '
                                    'problem-solving, and the typical '
                                    'consulting toolkit (slide-craft, Excel '
                                    'modeling, executive communication). '
                                    'Recent project work involved AI-strategy '
                                    'advisory but my own technical depth in AI '
                                    'is limited.',
                     'duration_months': 24,
                     'end_date': '2018-05-25',
                     'industry': 'Software',
                     'is_current': False,
                     'start_date': '2016-06-04',
                     'title': 'HR Manager'},
                    {'company': 'TCS',
                     'company_size': '10001+',
                     'description': 'Customer support team lead at a SaaS '
                                    'product. Managed a team of 8 support '
                                    'agents handling tier-1 and tier-2 '
                                    'tickets; owned the escalation process to '
                                    'engineering and the customer-feedback '
                                    'loop to product. Built out the support '
                                    'knowledge base and the agent training '
                                    'program. Strong on the people-management '
                                    'side and the process side; lighter on '
                                    'technical depth beyond product expertise.',
                     'duration_months': 9,
                     'end_date': '2016-06-04',
                     'industry': 'IT Services',
                     'is_current': False,
                     'start_date': '2015-09-08',
                     'title': 'Accountant'}],
 'certifications': [],
 'education': [{'degree': 'M.Sc',
                'end_year': 2012,
                'field_of_study': 'Information Technology',
                'grade': '87%',
                'institution': 'Chandigarh University',
                'start_year': 2007,
                'tier': 'tier_3'}],
 'languages': [{'language': 'English', 'proficiency': 'professional'},
               {'language': 'Hindi', 'proficiency': 'conversational'}],
 'profile': {'anonymized_name': 'Aisha Sethi',
             'country': 'India',
             'current_company': 'Stark Industries',
             'current_company_size': '1001-5000',
             'current_industry': 'Manufacturing',
             'current_title': 'Accountant',
             'headline': 'Accountant | Helping teams scale',
             'location': 'Gurgaon, Haryana',
             'summary': "Professional with 11.0+ years of experience. I've "
                        'spent my career in marketing manager roles, mostly '
                        'focused on driving outcomes through process, people, '
                        "and customer relationships. Lately I've been curious "
                        "about how AI tools could augment my work — I've "
                        'experimented with ChatGPT and a few other tools for '
                        'productivity and content creation, and I think the '
                        'space is exciting. Open to roles where I can apply my '
                        'domain expertise alongside emerging AI capabilities.',
             'years_of_experience': 11.0},
 'redrob_signals': {'applications_submitted_30d': 2,
                    'avg_response_time_hours': 116.7,
                    'connection_count': 300,
                    'endorsements_received': 14,
                    'expected_salary_range_inr_lpa': {'max': 19.7, 'min': 12.4},
                    'github_activity_score': -1,
                    'interview_completion_rate': 0.74,
                    'last_active_date': '2025-10-01',
                    'linkedin_connected': True,
                    'notice_period_days': 30,
                    'offer_acceptance_rate': -1,
                    'open_to_work_flag': True,
                    'preferred_work_mode': 'hybrid',
                    'profile_completeness_score': 84.6,
                    'profile_views_received_30d': 12,
                    'recruiter_response_rate': 0.37,
                    'saved_by_recruiters_30d': 1,
                    'search_appearance_30d': 67,
                    'signup_date': '2023-10-07',
                    'skill_assessment_scores': {},
                    'verified_email': False,
                    'verified_phone': True,
                    'willing_to_relocate': True},
 'skills': [{'duration_months': 12,
             'endorsements': 12,
             'name': 'SQL',
             'proficiency': 'beginner'},
            {'duration_months': 14,
             'endorsements': 6,
             'name': 'PowerPoint',
             'proficiency': 'beginner'},
            {'duration_months': 18,
             'endorsements': 4,
             'name': 'Photoshop',
             'proficiency': 'beginner'},
            {'duration_months': 35,
             'endorsements': 15,
             'name': 'Tailwind',
             'proficiency': 'intermediate'},
            {'duration_months': 30,
             'endorsements': 1,
             'name': 'Apache Flink',
             'proficiency': 'intermediate'},
            {'duration_months': 38,
             'endorsements': 50,
             'name': 'Image Classification',
             'proficiency': 'advanced'}]}

Dataset Profiling

In [12]:
import json
import pandas as pd
from tqdm import tqdm

In [13]:
candidates = []

with open(jsonl_path, "r") as f:
    for i, line in enumerate(f):
        candidates.append(json.loads(line))

        if i == 999:
            break

print(len(candidates))

1000

In [14]:
profiles = []

for c in candidates:
    p = c["profile"]

    profiles.append({
        "candidate_id": c["candidate_id"],
        "experience": p["years_of_experience"],
        "title": p["current_title"],
        "industry": p["current_industry"],
        "country": p["country"]
    })

profiles_df = pd.DataFrame(profiles)
profiles_df.head()

   candidate_id  experience               title        industry    country
0  CAND_0000001         6.9    Backend Engineer     IT Services     Canada
1  CAND_0000002        12.5  Operations Manager     IT Services      India
2  CAND_0000003         1.1    Customer Support     IT Services        USA
3  CAND_0000004         3.8   Marketing Manager  Paper Products  Australia
4  CAND_0000005        11.0          Accountant   Manufacturing      India

In [15]:
profiles_df["experience"].describe()

count    1000.00000
mean        6.89280
std         3.76027
min         1.10000
25%         3.70000
50%         6.30000
75%         9.70000
max        15.00000
Name: experience, dtype: float64

In [16]:
profiles_df["industry"].value_counts().head(20)

industry
IT Services          295
Manufacturing        226
Software             214
Paper Products        73
Conglomerate          71
Food Delivery         35
Fintech               33
Consulting            19
E-commerce            12
EdTech                 9
SaaS                   3
Gaming                 2
AI/ML                  2
HealthTech             2
Transportation         1
Conversational AI      1
AdTech                 1
HealthTech AI          1
Name: count, dtype: int64

In [17]:
skill_counts = []

for c in candidates:
    skill_counts.append(len(c["skills"]))

pd.Series(skill_counts).describe()

count    1000.000000
mean        9.602000
std         3.236676
min         5.000000
25%         7.000000
50%         9.000000
75%        11.000000
max        23.000000
dtype: float64

In [18]:
github_scores = []

for c in candidates:
    github_scores.append(
        c["redrob_signals"]["github_activity_score"]
    )

pd.Series(github_scores).describe()

count    1000.00000
mean        9.42950
std        17.79883
min        -1.00000
25%        -1.00000
50%        -1.00000
75%        15.70000
max        79.40000
dtype: float64

In [19]:
response_rates = []

for c in candidates:
    response_rates.append(
        c["redrob_signals"]["recruiter_response_rate"]
    )

pd.Series(response_rates).describe()

count    1000.000000
mean        0.433280
std         0.213356
min         0.040000
25%         0.247500
50%         0.430000
75%         0.610000
max         0.910000
dtype: float64

In [20]:
otw = []

for c in candidates:
    otw.append(
        c["redrob_signals"]["open_to_work_flag"]
    )

pd.Series(otw).value_counts()

False    654
True     346
Name: count, dtype: int64

In [21]:
assessment_lengths = []

for c in candidates:
    scores = c["redrob_signals"][
        "skill_assessment_scores"
    ]

    assessment_lengths.append(len(scores))

pd.Series(assessment_lengths).describe()

count    1000.000000
mean        0.361000
std         0.774131
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         5.000000
dtype: float64

Insight 1

AI industries are rare.

Insight 2

GitHub is rare.

Insight 3

Assessments are rare.

Insight 4

Open-to-work is rare.

Insight 5

Behavior signals seem intentionally useful.

In [22]:
titles = []

for c in candidates:
    titles.append(
        c["profile"]["current_title"]
    )

pd.Series(titles).value_counts().head(30)

Mechanical Engineer         70
Marketing Manager           69
Business Analyst            58
Customer Support            58
Sales Executive             57
Civil Engineer              55
HR Manager                  55
Graphic Designer            55
Project Manager             54
Operations Manager          51
Accountant                  51
Content Writer              48
Software Engineer           40
Frontend Engineer           39
QA Engineer                 35
Java Developer              29
DevOps Engineer             27
Cloud Engineer              27
Mobile Developer            26
Full Stack Developer        25
.NET Developer              19
Backend Engineer             9
Data Analyst                 9
Analytics Engineer           8
Senior Software Engineer     7
Data Engineer                6
Senior Data Engineer         3
AI Specialist                3
ML Engineer                  3
AI Research Engineer         2
Name: count, dtype: int64

In [23]:
skills = []

for c in candidates:
    for s in c["skills"]:
        skills.append(s["name"])

pd.Series(skills).value_counts().head(50)

Agile              144
JavaScript         143
Data Pipelines     141
Content Writing    136
AWS                134
HTML               134
Databricks         133
Accounting         132
Sales              132
Scrum              131
Apache Flink       128
Spark              128
Flask              127
gRPC               127
Kubernetes         126
TypeScript         126
Rust               126
Illustrator        126
Snowflake          125
Tailwind           125
SAP                125
SEO                125
Six Sigma          124
SQL                124
REST APIs          124
GCP                124
React              124
Next.js            123
Airflow            123
Terraform          122
Redis              122
Docker             122
Azure              121
Vue.js             121
Django             121
ETL                121
MongoDB            120
Salesforce CRM     120
Java               119
PostgreSQL         119
GraphQL            118
Spring Boot        117
Excel              117
Apache Beam        116
Figma              115
Hadoop             115
Marketing          113
Redux              110
Angular            110
dbt                109
Name: count, dtype: int64

In [24]:
sizes = []

for c in candidates:
    sizes.append(
        c["profile"]["current_company_size"]
    )

pd.Series(sizes).value_counts()

10001+        400
1001-5000     169
201-500       157
11-50          79
501-1000       76
51-200         73
5001-10000     46
Name: count, dtype: int64

In [25]:
notice = []

for c in candidates:
    notice.append(
        c["redrob_signals"]
        ["notice_period_days"]
    )

pd.Series(notice).describe()

count    1000.000000
mean       87.165000
std        36.196657
min        30.000000
25%        60.000000
50%        90.000000
75%       120.000000
max       150.000000
dtype: float64

In [26]:
saved = []

for c in candidates:
    saved.append(
        c["redrob_signals"]
        ["saved_by_recruiters_30d"]
    )

pd.Series(saved).describe()

count    1000.000000
mean        7.371000
std         5.537511
min         0.000000
25%         3.000000
50%         7.000000
75%        10.250000
max        45.000000
dtype: float64

In [27]:
completion = []

for c in candidates:
    completion.append(
        c["redrob_signals"]
        ["interview_completion_rate"]
    )

pd.Series(completion).describe()

count    1000.000000
mean        0.616170
std         0.170142
min         0.300000
25%         0.480000
50%         0.610000
75%         0.760000
max         0.990000
dtype: float64